// Cached DOM element references. Imported as a module, so this runs after the
// document is parsed (deferred), meaning every lookup resolves.

export const canvas = document.getElementById("game");
export const ctx = canvas.getContext("2d");

export const livesEl = document.getElementById("lives");
export const waveTextEl = document.getElementById("waveText");
export const waveFillEl = document.getElementById("waveFill");
export const waveBarEl = document.getElementById("waveBar");
export const tick1El = document.querySelector(".tick1");
export const tick2El = document.querySelector(".tick2");
export const waveAnnounceEl = document.getElementById("waveAnnounce");
export const breatherEl = document.getElementById("breather");
export const breatherCountEl = document.getElementById("breatherCount");
export const streakEl = document.getElementById("streak");
export const streakValueEl = document.getElementById("streakValue");
export const streakMultEl = document.getElementById("streakMult");
export const scoreHudEl = document.getElementById("scoreHud");
export const scoreValueEl = document.getElementById("scoreValue");
export const gameOverEl = document.getElementById("gameover");
export const finalScoreEl = document.getElementById("finalScore");
export const gameOverTitleEl = document.getElementById("gameoverTitle");
export const victoryStarsEl = document.getElementById("victoryStars");
export const inputValueEl = document.getElementById("inputValue");
export const pausedEl = document.getElementById("paused");
export const restartBtnEl  = document.getElementById("restartBtn");
export const worldMapBtnEl = document.getElementById("worldMapBtn");
export const homeBtnEl     = document.getElementById("homeBtn");
// menu screens (home + world selection) shown before a run starts
export const homeScreenEl = document.getElementById("homeScreen");
export const worldScreenEl = document.getElementById("worldScreen");
export const homePlayBtnEl = document.getElementById("homePlayBtn");
export const worldCardBtnEl = document.getElementById("worldCardBtn");
export const worldBackBtnEl = document.getElementById("worldBackBtn");
export const worldPlayBtnEl = document.getElementById("worldPlayBtn");
export const levelMapEl = document.querySelector(".levelMap");
export const worldPrevBtnEl = document.getElementById("worldPrevBtn");
export const worldNextBtnEl = document.getElementById("worldNextBtn");
export const worldNavTitleEl = document.getElementById("worldNavTitle");
export const worldProgressFillEl = document.getElementById("worldProgressFill");
export const worldProgressTextEl = document.getElementById("worldProgressText");
export const worldPlayLabelEl = document.getElementById("worldPlayLabel");
export const worldHeaderKickerEl = document.getElementById("worldHeaderKicker");
export const worldHeaderNameEl = document.getElementById("worldHeaderName");
export const worldStarBadgeEl = document.getElementById("worldStarBadge");
// home screen dynamic bits
export const homeWorldKickerEl = document.getElementById("homeWorldKicker");
export const homeWorldNameEl = document.getElementById("homeWorldName");
export const homeWorldFillEl = document.getElementById("homeWorldFill");
export const homeWorldProgressEl = document.getElementById("homeWorldProgress");
export const homeStarsEl = document.getElementById("homeStars");
export const homePlaySubEl = document.getElementById("homePlaySub");
export const profileNameEl = document.getElementById("profileName");
export const profileAvatarEl = document.getElementById("profileAvatar");
export const profileStarsEl = document.getElementById("profileStars");
export const homePlayerDmgEl    = document.getElementById("homePlayerDmg");
export const homePlayerDmgSubEl = document.getElementById("homePlayerDmgSub");
export const homeMaxHpEl = document.getElementById("homeMaxHp");
export const homeXpFillEl = document.getElementById("homeXpFill");
export const homeXpLabelEl = document.getElementById("homeXpLabel");
export const diffPillsEl = document.getElementById("diffPills");
// victory XP gain section
export const xpGainEl      = document.getElementById("xpGain");
export const xpGainAmtEl   = document.getElementById("xpGainAmt");
export const xpGainFillEl  = document.getElementById("xpGainFill");
export const xpGainLevelEl = document.getElementById("xpGainLevel");
export const xpReplayTipEl = document.getElementById("xpReplayTip");
export const bossAlertEl = document.getElementById("bossAlert");
export const inputBoxEl = document.getElementById("inputBox");
export const chipBarEl = document.getElementById("chipBar");
export const menuBgmEl        = document.getElementById("menuBgm");
export const bgmEl            = document.getElementById("bgm");
export const levelSuccessSfxEl = document.getElementById("levelSuccessSfx");
export const gameOverSfxEl    = document.getElementById("gameOverSfx");
export const laserSfxEl       = document.getElementById("laserSfx");
export const muteBtnEl        = document.getElementById("muteBtn");
export const homeMuteBtnEl    = document.getElementById("homeMuteBtn");
